#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 14 17:58:56 2021

@author: Patrick
"""
import pandas as pd
import numpy as np
from sklearn import tree

Titanic = pd.read_csv("/Users/schuermi/Desktop/minichallenge_titanic.csv")

TitanicDescribe = Titanic.describe()
TitanicType = Titanic.dtypes
TitanicSurvived = Titanic["Survived"]
TitanicFemale = Titanic["Sex"]

Titanic["ChildAdult"] = np.where(Titanic['Age'] <= 18, "Child", "Adult")
Titanic["NoFamilymembers"] = Titanic["SibSp"] + Titanic["Parch"]

grouped_Titanic = Titanic.groupby(["Sex", "Survived"]).size().unstack(fill_value=0)
grouped_Titanic.plot.bar()

Titanic.hist(column="Age")
Titanic.hist(column="Fare")
Titanic.boxplot(column='Fare', by=["Survived"])
Titanic.boxplot(column='Age', by=["Survived"])
Titanic.boxplot(column='NoFamilymembers', by=["Survived"])
